input {
  file {
    path => "/home/sudeep/CyArt-SOC-Domain-Task-1st-week-/Theoretical-Knowledge/Task3-Log-Management-Fundamentals/apache.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{IP:clientip} %{DATA:ident} %{DATA:auth} \[%{DATA:timestamp}\] \"%{WORD:verb} %{DATA:request} HTTP/%{NUMBER:httpversion}\" %{NUMBER:response} %{NUMBER:bytes}"
    }
  }
}

output {
  stdout { codec => rubydebug }

  file {
    path => "/home/sudeep/apache_json_logs.json"
    codec => json
  }
}
